#build stage
FROM node:current-alpine3.21 AS build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build
#production stage
FROM build AS production
COPY --from=build ./app/.next ./.next
COPY --from=build ./app/public ./public
COPY --from=build ./app/package*.json ./
COPY --from=build ./app/node_modules ./node_modules
CMD npm start
